name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    outputs:
      build-success: ${{ steps.build-status.outputs.success }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout bitcoinfuzz repo
        uses: actions/checkout@v4
        with:
          repository: bitcoinfuzz/bitcoinfuzz
          path: bitcoinfuzz
          submodules: recursive

      - name: Install rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Setup Python and install embit
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r bitcoinfuzz/modules/embit/requirements.txt
          pip install mako

      - name: Install LLVM and Clang - Ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo ln -sfT clang++-18 /usr/bin/clang++
          sudo ln -sfT clang-18 /usr/bin/clang
          # Set environment variables for all subsequent steps
          echo "CC=/usr/bin/clang-18" >> $GITHUB_ENV
          echo "CXX=/usr/bin/clang++-18" >> $GITHUB_ENV

      - name: Install LLVM and Clang - macOS
        if: matrix.os == 'macos-14'
        run: |
          brew install llvm@18
          # Add LLVM to PATH for all subsequent steps
          echo "$(brew --prefix llvm@18)/bin" >> $GITHUB_PATH
          echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV

      - name: Install build dependencies - Ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool gettext pkg-config protobuf-compiler libsodium-dev

      - name: Install build dependencies - macOS
        if: matrix.os == 'macos-14'
        run: |
          brew install autoconf gnu-sed automake libtool gettext pkg-config protobuf libsodium

      - name: Verify compiler setup
        run: |
          echo "CC: $CC"
          echo "CXX: $CXX"
          $CC --version
          $CXX --version
          which clang
          which clang++

      - name: Build - Bitcoin Core
        timeout-minutes: 40
        run: |
          cd bitcoinfuzz/modules/bitcoin && make

      - name: Build - custommutator
        timeout-minutes: 40
        run: |
          cd bitcoinfuzz/modules/custommutator && make

      - name: Build - rust bitcoin
        timeout-minutes: 5
        run: |
          rustup default nightly
          cd bitcoinfuzz/modules/rustbitcoin && make cargo && make

      - name: Build - rust miniscript
        timeout-minutes: 5
        run: |
          rustup default nightly
          cd bitcoinfuzz/modules/rustminiscript && make cargo && make

      - name: Build - btcd
        timeout-minutes: 5
        run: |
          cd bitcoinfuzz/modules/btcd && make

      - name: Build - embit
        timeout-minutes: 5
        run: |
          cd bitcoinfuzz/modules/embit && make

      - name: Build - lnd
        timeout-minutes: 5
        run: |
          cd bitcoinfuzz/modules/lnd && make

      - name: Build - ldk
        timeout-minutes: 5
        run: |
          rustup default nightly
          cd bitcoinfuzz/modules/ldk && make cargo && make

      - name: Build - nlightning
        timeout-minutes: 5
        run: |
          cd bitcoinfuzz/modules/nlightning && make

      - name: Build - clightning
        timeout-minutes: 5
        run: |
          cd bitcoinfuzz/modules/clightning && make

      - name: Pre-build main executables
        run: |
          cd bitcoinfuzz
          # Build different configurations that will be needed for tests
          export CXXFLAGS="-DBITCOIN_CORE -DRUST_BITCOIN"
          make && cp bitcoinfuzz bitcoinfuzz_script

          export CXXFLAGS="-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD"
          make && cp bitcoinfuzz bitcoinfuzz_deserialize_block

          export CXXFLAGS="-DBITCOIN_CORE -DBTCD"
          make && cp bitcoinfuzz bitcoinfuzz_script_eval

          export CXXFLAGS="-DBITCOIN_CORE -DRUST_MINISCRIPT"
          make && cp bitcoinfuzz bitcoinfuzz_descriptor

          export CXXFLAGS="-DRUST_BITCOIN -DBTCD"
          make && cp bitcoinfuzz bitcoinfuzz_psbt

          export CXXFLAGS="-DLDK -DLND -DCLIGHTNING -DCUSTOM_MUTATOR_BOLT11"
          (cd ./modules/bitcoin && make clean)
          make && cp bitcoinfuzz bitcoinfuzz_invoice

          export CXXFLAGS="-DLDK -DCLIGHTNING"
          make && cp bitcoinfuzz bitcoinfuzz_offer

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ matrix.os }}-

      - name: Set build status
        id: build-status
        run: echo "success=true" >> $GITHUB_OUTPUT

  test-script:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ matrix.os }}-

      - name: Test - script
        timeout-minutes: 5
        run: |
          if [ -d "./script" ]; then
            cd bitcoinfuzz
            echo "Using corpora for script"
            cp bitcoinfuzz_script bitcoinfuzz
            FUZZ=script ./bitcoinfuzz -runs=1 ../script
          else
            echo "No script test data found, skipping"
          fi

  test-deserialize-block:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - deserialize_block
        timeout-minutes: 5
        run: |
          if [ -d "./deserialize_block" ]; then
            cd bitcoinfuzz
            echo "Using corpora for deserialize_block"
            cp bitcoinfuzz_deserialize_block bitcoinfuzz
            FUZZ=deserialize_block ./bitcoinfuzz -runs=1 ../deserialize_block
          else
            echo "No deserialize_block test data found, skipping"
          fi

  test-script-eval:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - script_eval
        timeout-minutes: 5
        run: |
          if [ -d "./script_eval" ]; then
            cd bitcoinfuzz
            echo "Using corpora for script_eval"
            cp bitcoinfuzz_script_eval bitcoinfuzz
            FUZZ=script_eval ./bitcoinfuzz -runs=1 ../script_eval
          else
            echo "No script_eval test data found, skipping"
          fi

  test-descriptor-parse:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - descriptor_parse
        timeout-minutes: 5
        run: |
          if [ -d "./descriptor_parse" ]; then
            cd bitcoinfuzz
            echo "Using corpora for descriptor_parse"
            cp bitcoinfuzz_descriptor bitcoinfuzz
            ASAN_OPTIONS=detect_leaks=0 FUZZ=descriptor_parse ./bitcoinfuzz -runs=1 ../descriptor_parse
          else
            echo "No descriptor_parse test data found, skipping"
          fi

  test-miniscript-parse:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - miniscript_parse
        run: |
          if [ -d "./miniscript_parse" ]; then
            cd bitcoinfuzz
            echo "Using corpora for miniscript_parse"
            cp bitcoinfuzz_descriptor bitcoinfuzz
            ASAN_OPTIONS=detect_leaks=0 FUZZ=miniscript_parse ./bitcoinfuzz -runs=1 ../miniscript_parse
          else
            echo "No miniscript_parse test data found, skipping"
          fi

  test-script-asm:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - script_asm
        run: |
          if [ -d "./script_asm" ]; then
            cd bitcoinfuzz
            echo "Using corpora for script_asm"
            cp bitcoinfuzz_script_eval bitcoinfuzz
            FUZZ=script_asm ./bitcoinfuzz -runs=1 ../script_asm
          else
            echo "No script_asm test data found, skipping"
          fi

  test-address-parse:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - address_parse
        run: |
          if [ -d "./address_parse" ]; then
            cd bitcoinfuzz
            echo "Using corpora for address_parse"
            cp bitcoinfuzz_script bitcoinfuzz
            FUZZ=address_parse ./bitcoinfuzz -runs=1 ../address_parse
          else
            echo "No address_parse test data found, skipping"
          fi

  test-psbt-parse:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - psbt_parse
        run: |
          if [ -d "./psbt_parse" ]; then
            cd bitcoinfuzz
            echo "Using corpora for psbt_parse"
            cp bitcoinfuzz_psbt bitcoinfuzz
            ASAN_OPTIONS=detect_leaks=0 FUZZ=psbt_parse ./bitcoinfuzz -runs=1 ../psbt_parse
          else
            echo "No psbt_parse test data found, skipping"
          fi

  test-deserialize-invoice:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - deserialize_invoice
        run: |
          if [ -d "./deserialize_invoice" ]; then
            cd bitcoinfuzz
            echo "Using corpora for deserialize_invoice"
            cp bitcoinfuzz_invoice bitcoinfuzz
            ASAN_OPTIONS=detect_leaks=0 FUZZ=deserialize_invoice ./bitcoinfuzz -runs=1 ../deserialize_invoice
          else
            echo "No deserialize_invoice test data found, skipping"
          fi

  test-deserialize-offer:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore build artifacts
        uses: actions/cache@v4
        with:
          path: bitcoinfuzz/
          key: build-${{ matrix.os }}-${{ github.sha }}

      - name: Test - deserialize_offer
        run: |
          if [ -d "./deserialize_offer" ]; then
            cd bitcoinfuzz
            echo "Using corpora for deserialize_offer"
            cp bitcoinfuzz_offer bitcoinfuzz
            ASAN_OPTIONS=detect_leaks=0 FUZZ=deserialize_offer ./bitcoinfuzz -runs=1 ../deserialize_offer
          else
            echo "No deserialize_offer test data found, skipping"
          fi
